language = "C" 

include_guard = "PEPPER_PLUGIN_API_H"
no_includes = true
documentation = true

style = "tag"

[export]
prefix = "Pepper_"
include = ["PluginApi"]
item_types = ["structs", "opaque", "functions"]
