language = "C" 

include_guard = "PEPPER_PLUGIN_API_H"
no_includes = true
documentation = true

style = "tag"

[export]
prefix = "Pepper"
include = ["PluginApi", "PluginCommandFn"]
item_types = ["structs", "opaque", "typedefs"]

[parse]
parse_deps = false
