[package]
name = "mine"
version = "0.1.0"
edition = "2018"
publish = false

[[bin]]
name = "pepper"
path = "src/main.rs"

[dependencies]
pepper = { path = "../pepper" }
pepper-plugin-lsp = { path = "../plugin-lsp" }
